### ISSUE TITLE
Use getBoundingClientRect() instead of .offsetLeft for computing elementX in MousePosition

### ISSUE THREAD

**Issue by ncknuna** [jaredLunde/render-props#1]
First of all, cool library :)

I was trying to use elementX to get the current mouse position relative to the ref'd element, but found that .offsetLeft gets the left offset of the ref'd element relative to the offsetParent, not the position on the page, which MDN suggests using `getBoundingClientRect` for instead (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetLeft). 

If that's not the purpose of elementX, I'd love if we could add an extra prop for what I'm looking for. Happy to send a PR if you'd like :)

**Comment by jaredLunde** [comment]
Ahh, you're correct

https://github.com/jaredLunde/render-props/blob/master/packages/mouse-position/src/MousePosition.js#L117
```js
const {clientX, clientY, screenX, screenY, pageX, pageY} = e
const elementX = pageX - this.element.offsetLeft
const elementY = pageY - this.element.offsetTop
```

The above should probably be something like:
```js
const {clientX, clientY, screenX, screenY, pageX, pageY} = e
const rect = this.element.getClientBoundingRect()
const elementX = pageX - rect.left
const elementY = pageY - rect.top
```

Sorry about that! I'll put in a patch for this today unless you're itching to submit a PR.

**Comment by ncknuna** [comment]
Yup, that looks like the right solution!

Nah, no itching here, go for it :)

**Comment by jaredLunde** [comment]
Just published a patch. Thanks for you report!
